name: Manage labels of reward redeem flow
on:
    pull_request:
        types: [opened, labeled, closed, merged]
    issues:
        types: [opened, labeled, closed]
jobs:
    validate-files:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: NPM Install
              run: npm install
              shell: bash
            - name: Validate Files
              run: npm run validate && npm run lint
              shell: bash
    redeem-rewards:
        needs: validate-files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: NPM Install
              run: npm install
              shell: bash
            - name: Push assets to server
              env:
                  MAIN_API_ENDPOINT: ${{ secrets.MAIN_API_ENDPOINT }}
                  MAIN_API_TOKEN: ${{ secrets.API_ASSETS_KEY }}
              run: |
                  npm run redeem:rewards
              shell: bash
